openapi: 3.0.0
info:
  title: TypeScript Boilerplate
  description: This is typescript boilerplate's API specification.
  version: 1.0.0
servers:
- url: https://localhost:3000/api
tags:
- name: Books
  description: Books related API
paths:

  securitySchemes:
    Bearer:
      type: apiKey
      description: Example value:- Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU5MmQwMGJhNTJjYjJjM
      name: Authorization
      in: header
